baseURL = '/'
languageCode = 'pl'
defaultContentLanguage = "pl"
enableGitInfo = true

title = 'letsweb.biz'

[imageProcessing]
    enableExternal = true
    externalCommands = ["gm"]

[frontmatter]
    date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
    expiryDate = ['expirydate', 'unpublishdate']
    lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
    publishDate = ['publishdate', 'pubdate', 'published', 'date']

[taxonomies]
    tag = "tags"

[languages]
    [languages.pl]
        weight = 1
        languageName = "Polish"
        contentDir = "content/pl"

    [languages.en]
        weight = 2
        languageName = "English"
        contentDir = "content/en"

[markup]
[markup.goldmark.renderer]
    unsafe = true