baseURL = 'https://tomqsm.github.io/lgs-letsweb-github-site'
languageCode = 'pl-pl'
title = 'letsweb.biz'

[imageProcessing]
    enableExternal = true
    externalCommands = ["gm"]

[taxonomies]
    tag = "tags"
