baseURL = 'https://tomqsm.github.io/lgs-letsweb-github-site'
languageCode = 'pl'
defaultContentLanguage = "pl"
enableGitInfo = true

title = 'letsweb.biz'

[imageProcessing]
    enableExternal = true
    externalCommands = ["gm"]

[taxonomies]
    tag = "tags"

[languages]
    [languages.pl]
        weight = 1
        languageName = "Polish"
        contentDir = "content/pl"

    [languages.en]
        weight = 2
        languageName = "English"
        contentDir = "content/en"

[markup]
[markup.goldmark.renderer]
    unsafe = true