# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["gcp"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.114.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Authenticating via Workload Identity Federation
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SA_EMAIL }}

      - name: Exec a command in VM
        id: compute-ssh
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'hatjump'
          zone: 'europe-central2-a'
          ssh_private_key: '${{ secrets.HATJUMP }}'
          command: 'echo Hello world'

      - name: Print 'Exec a command in VM' output
        run: |-
          echo '${{ steps.compute-ssh.outputs.stdout }}'
          echo '${{ steps.compute-ssh.outputs.stderr }}'

      - name: Copy directory to VM
        run: |-
          gcloud compute scp --zone europe-central2-a --recurse ~/wardrobe hatjump:~/narnia